// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.771
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Greeting() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"grid grid-cols-4 place-items-center\"><a href=\"https://github.com/Marattttt/\" target=\"blank\"><img class=\"size-44 col-span-1 rounded-full border-2\n\t\t\tborder-amber-100\n\t\t\ttransition-colors duration-200\n\t\t\thover:border-orange-400\n\t\t\" src=\"/static/img/github-profile-pic.png\"></a><div class=\"p-5 col-start-2 col-end-7 space-y-6 text-amber-100\"><div class=\"m-b-5 w-fit\"><h1 class=\"text-5xl p-b-20 underline decoration-orange-400\">Marat Bakasov</h1><h2 class=\"text-xl\">Backend developer</h2></div><div><p class=\"whitespace-normal\">Hello and welcome to my page :) <br>I am a developer from Bishkek, Kyrgyz Republic <br>This website is currently a <b>work in progress</b>, is built with Go+HTMX+tailwind as I think this is the most comfortable way to achieve everything this project will need in the future as very little, if at all, Js is required for it</p></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
